/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

--Finding total customers by area
SELECT
area,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY area
ORDER BY total_customers DESC

--Finding total customers by segment
SELECT
customer_segment,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY customer_segment
ORDER BY total_customers DESC

--Finding total products by category
SELECT 
category,
COUNT(product_id) AS total_products
FROM gold.fact_orders
GROUP BY category
ORDER BY total_products DESC

--what is the average cost in each category
SELECT
category,
AVG(total_cost) AS avg_cost
FROM gold.fact_orders
GROUP BY category
order by avg_cost DESC

--what is the total revenue generated for each category
SELECT 
category,
SUM(total_cost) AS total_revenue
FROM gold.fact_orders
GROUP BY category
ORDER BY total_revenue

--Finding the total revenue generated by each customer
SELECT
customer_id,
customer_name,
SUM(total_cost) AS total_revenue
from gold.fact_orders
GROUP BY customer_id,customer_name
ORDER BY total_revenue DESC

--what is the distribution of sold items across areas
SELECT
area,
SUM(quantity) AS distribution
FROM gold.fact_orders
GROUP BY area
ORDER BY distribution DESC

SELECT
    area,
    SUM(total_cost) AS total_revenue
FROM gold.fact_orders
GROUP BY area
ORDER BY total_revenue DESC;
